// If the application is self hoisted on the web, the IPC interface wont be available.
// Here we define a dummy interface to make the ui work.

if (!window.csdm) {
  window.csdm = {
    logger: {
      log: () => {},
      warn: () => {},
      error: () => {},
      getLogFilePath: () => '',
      clear: async () => {},
    },
    ADDITIONAL_ARGUMENTS: [],
    IMAGES_FOLDER_PATH: 'static\\images',
    platform: 'win32',
    isMac: false,
    isWindows: false,
    isLinux: false,
    isWeb: true,
    unknownMapThumbnailFilePath: 'static\\images\\maps\\thumbnail_unknown.png',
    browseToFile: () => undefined,
    browseToFolder: () => undefined,
    canGoBack: async () => false,
    canGoForward: async () => false,
    clearStartupArguments: () => undefined,
    closeWindow: () => undefined,
    elementToImage: async () => undefined,
    getAppInformation: () => undefined,
    getAudio: () => undefined,
    getDefaultPlayerAvatar: () => undefined,
    getFfmpegExecutablePath: () => undefined,
    getHlaeExecutablePath: () => undefined,
    getMapLowerRadarBase64: () => undefined,
    getMapRadarBase64: () => undefined,
    getMapThumbnailBase64: () => undefined,
    getPathDirectoryName: () => undefined,
    getPngInformation: () => undefined,
    getPremierRankImageSrc: () => undefined,
    getRankImageSrc: () => undefined,
    getStartupArguments: async () => [],
    getSystemStartupBehavior: () => undefined,
    getTheme: () => undefined,
    getVirtualDubExecutablePath: () => undefined,
    hasUpdateReadyToInstall: async () => false,
    installUpdate: () => undefined,
    isWindowMaximized: () => false,
    localeChanged: () => undefined,
    maximizeWindow: () => undefined,
    minimizeWindow: () => undefined,
    onNavigateToBans: () => () => undefined,
    onNavigateToPendingDownloads: () => () => undefined,
    onOpenDemoFile: () => () => undefined,
    onOpenSettings: () => () => undefined,
    onShowAbout: () => () => undefined,
    onToggleSettingsVisibility: () => () => undefined,
    onUpdateDownloaded: () => () => undefined,
    onWindowClose: () => () => undefined,
    onWindowMaximized: () => () => undefined,
    onWindowUnMaximized: () => () => undefined,
    parseSettingsFile: () => undefined,
    pathExists: () => undefined,
    readTableState: () => [],
    reloadWindow: () => undefined,
    resetSettings: () => undefined,
    restartApp: () => undefined,
    showMainWindow: () => undefined,
    showOpenDialog: () => undefined,
    showSaveDialog: () => undefined,
    showTitleBarMenu: () => undefined,
    toggleAutoDownloadUpdates: () => undefined,
    unMaximizeWindow: () => undefined,
    updateSettings: async () => {},
    updateSystemStartupBehavior: async () => {},
    writeTableState: async () => {},
  };
}
